name: Laravel CI/CD

on:
  push:
    branches:
      - master # deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo, tokenizer
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload to Home.pl via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: ~/.ssh/id_rsa
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            cd ~/public_html/api.mamfachowca.mosioneklukasz.pl
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
